"""Law 4 — Flow-of-funds transactions-vs-positions identity (project plan §1.1).

Change in arc weight between adjacent periods equals net transactions plus
revaluation:

.. math::

    x_{ij}^{k}(t+1) - x_{ij}^{k}(t)
    = F_{ij}^{k}(t \\to t+1) + R_{ij}^{k}(t \\to t+1)

where :math:`F` is net new transactions (issuance minus redemption, from Z.1
F.tables) and :math:`R` is mark-to-market revaluation (zero for book-value
arcs).  The Z.1 publishes both stock (``L.*`` tables) and flow (``F.*`` tables)
consistently, supplying two independent constraints per period.

Constraints are emitted only for arcs present in *flow_terms*: if no
transaction data is available for an arc, no constraint is emitted (the arc
is free to change between periods, bounded only by Laws 1–3).

``DIRECT_MEASURED`` arcs in either period are folded into the right-hand side
as known constants; all other arcs remain as variables in the constraint
matrix row.  A single :class:`~claimweb.constraints.kcl.LinearConstraint` may
reference :class:`~claimweb.constraints.kcl.ArcKey`\\s from *both* periods
because the unknown arc variables span both period_from and period_to.

Public interface
----------------
``FlowKey``
    3-tuple ``(source_node_id, target_node_id, instrument_class_value)``
    used to look up transaction and revaluation terms.
``FlowTerms``
    ``dict[FlowKey, Decimal]`` — net transactions *F* in millions USD.
``RevaluationTerms``
    ``dict[FlowKey, Decimal]`` — revaluation *R* in millions USD.
``FlowFundsViolation``
    One arc that violates Law 4.
``FlowFundsResult``
    Aggregate result of :func:`check_flow_funds`.
``build_flow_funds_rows``
    Compile one :class:`~claimweb.constraints.kcl.LinearConstraint` per
    arc in *flow_terms*.
``check_flow_funds``
    Directly verify Law 4 on a pair of
    :class:`~claimweb.constraints.kcl.NetworkState` objects.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from decimal import Decimal

from claimweb.constraints.kcl import (
    _ZERO,
    ArcKey,
    ConstraintSet,
    LinearConstraint,
    NetworkState,
    _group_arcs_by_key,
    _group_arcs_by_key_with_flag,
)
from claimweb.fetchers.base import ArcFact, DataQualityFlag, Period

# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------

#: 3-tuple identifying one arc for flow/revaluation lookup.
FlowKey = tuple[str, str, str]

#: Mapping from FlowKey → net transactions F in millions USD (Z.1 F.tables).
FlowTerms = dict[FlowKey, Decimal]

#: Mapping from FlowKey → mark-to-market revaluation R in millions USD.
#: Absent keys default to zero (book-value arcs carry no revaluation).
RevaluationTerms = dict[FlowKey, Decimal]

# Relative tolerance: 0.1 % — consistent with Law 3; tighter than Z.1 rounding.
_DEFAULT_TOL_REL = Decimal("0.001")

# Absolute floor: $0.1 M — prevents spurious violations on tiny test networks.
_MIN_ABS_TOL = Decimal("0.1")

_ONE = Decimal("1")
_NEG_ONE = Decimal("-1")

# Regex that parses (source, target, instrument, period_from, period_to) from
# a Law 4 provenance string generated by this module.
_PROV_RE = re.compile(
    r"Law 4 \(flow-of-funds\) for arc '([^']+)' -> '([^']+)' "
    r"instrument '([^']+)', period '([^']+)' -> '([^']+)'"
)


# ---------------------------------------------------------------------------
# Result types
# ---------------------------------------------------------------------------


@dataclass
class FlowFundsViolation:
    """One arc that violates the flow-of-funds identity (Law 4)."""

    source_node_id: str
    target_node_id: str
    instrument_class_value: str
    period_from: Period
    period_to: Period
    amount_from: Decimal        # x(t) — arc value at period_from (0 if absent)
    amount_to: Decimal          # x(t+1) — arc value at period_to (0 if absent)
    flow_term: Decimal          # F — net transactions
    revaluation_term: Decimal   # R — mark-to-market revaluation
    expected_change: Decimal    # F + R
    actual_change: Decimal      # amount_to − amount_from
    residual: Decimal           # actual_change − expected_change (signed)
    provenance: str


@dataclass
class FlowFundsResult:
    """Aggregate result of :func:`check_flow_funds` on two network states."""

    period_from: Period
    period_to: Period
    satisfied: bool
    violations: list[FlowFundsViolation]
    arc_count: int      # distinct arcs present in the union of both networks
    checked_count: int  # arcs checked (those with a supplied flow term)


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _provenance_arc(
    provenance: str,
) -> tuple[str, str, str, str, str] | None:
    """Extract *(source, target, instrument, period_from, period_to)* from a
    Law 4 provenance string.  Returns ``None`` on parse failure.
    """
    m = _PROV_RE.search(provenance)
    if m:
        return m.group(1), m.group(2), m.group(3), m.group(4), m.group(5)
    return None


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_flow_funds_rows(
    facts_from: list[ArcFact],
    facts_to: list[ArcFact],
    *,
    period_from: Period,
    period_to: Period,
    flow_terms: FlowTerms | None = None,
    revaluation_terms: RevaluationTerms | None = None,
) -> ConstraintSet:
    """Compile one :class:`~claimweb.constraints.kcl.LinearConstraint` per
    arc in *flow_terms*.

    For each arc *(i, j, k)* present in *flow_terms* the generated equality is:

    .. math::

        x_{ij}^k(t+1) - x_{ij}^k(t) = F_{ij}^k + R_{ij}^k

    The constraint spans two periods, so its
    :attr:`~claimweb.constraints.kcl.LinearConstraint.matrix_row` may contain
    :class:`~claimweb.constraints.kcl.ArcKey`\\s from both *period_from* and
    *period_to*:

    * :class:`ArcKey` ``(i, j, k, period_to_str)`` with coefficient **+1**
    * :class:`ArcKey` ``(i, j, k, period_from_str)`` with coefficient **−1**

    ``DIRECT_MEASURED`` arcs are folded into the right-hand side:

    * If ``x(t)`` is ``DIRECT_MEASURED`` with value *a*:
      ``rhs = F + R + a``  (key_from absent from matrix_row)
    * If ``x(t+1)`` is ``DIRECT_MEASURED`` with value *b*:
      ``rhs = F + R − b``  (key_to absent from matrix_row)
    * If both are ``DIRECT_MEASURED``:
      ``rhs = F + R + a − b``, ``matrix_row`` is empty (pure check).

    When *flow_terms* is ``None`` or empty, no constraints are emitted —
    the arc is unconstrained across periods.

    Parameters
    ----------
    facts_from:
        :class:`~claimweb.fetchers.base.ArcFact`\\s for *period_from*.
        Facts with a different period are silently discarded.
    facts_to:
        :class:`~claimweb.fetchers.base.ArcFact`\\s for *period_to*.
        Facts with a different period are silently discarded.
    period_from:
        The earlier period.
    period_to:
        The later period.
    flow_terms:
        ``FlowKey → F`` mapping in millions USD.  Only arcs present here
        receive a constraint.  ``None`` or empty → empty
        :class:`~claimweb.constraints.kcl.ConstraintSet`.
    revaluation_terms:
        ``FlowKey → R`` mapping in millions USD.  Absent keys default to
        zero (book-value assumption).

    Returns
    -------
    ConstraintSet
        One :class:`~claimweb.constraints.kcl.LinearConstraint` per key in
        *flow_terms* (sorted by key), plus the list of all unknown
        :class:`~claimweb.constraints.kcl.ArcKey`\\s referenced.
    """
    if not flow_terms:
        return ConstraintSet(constraints=[], unknowns=[])

    period_from_str = str(period_from)
    period_to_str = str(period_to)

    arc_data_from = _group_arcs_by_key_with_flag(facts_from, period_from)
    arc_data_to = _group_arcs_by_key_with_flag(facts_to, period_to)

    if revaluation_terms is None:
        revaluation_terms = {}

    constraints: list[LinearConstraint] = []
    all_unknowns: set[ArcKey] = set()

    for flow_key in sorted(flow_terms):
        src, tgt, instr_val = flow_key
        f_term = flow_terms[flow_key]
        r_term = revaluation_terms.get(flow_key, _ZERO)
        rhs = f_term + r_term

        key_from: ArcKey = (src, tgt, instr_val, period_from_str)
        key_to: ArcKey = (src, tgt, instr_val, period_to_str)

        matrix_row: dict[ArcKey, Decimal] = {}

        # ---- period_from arc: coefficient −1 (moves to RHS if known) ----
        if key_from in arc_data_from:
            amount_from, flag_from = arc_data_from[key_from]
            if flag_from == DataQualityFlag.DIRECT_MEASURED:
                # x(t) known: x(t+1) − a_from = F + R → rhs += a_from
                rhs += amount_from
            else:
                matrix_row[key_from] = matrix_row.get(key_from, _ZERO) + _NEG_ONE
                all_unknowns.add(key_from)
        # Arc absent in period_from → treat as 0 (new arc); no variable added.

        # ---- period_to arc: coefficient +1 (moves to RHS if known) ----
        if key_to in arc_data_to:
            amount_to, flag_to = arc_data_to[key_to]
            if flag_to == DataQualityFlag.DIRECT_MEASURED:
                # x(t+1) known: a_to − x(t) = F + R → rhs -= a_to
                rhs -= amount_to
            else:
                matrix_row[key_to] = matrix_row.get(key_to, _ZERO) + _ONE
                all_unknowns.add(key_to)
        # Arc absent in period_to → treat as 0 (terminated arc); no variable added.

        # Drop any zero-coefficient entries that arise from opposing flags.
        matrix_row = {k: v for k, v in matrix_row.items() if v != _ZERO}

        constraints.append(
            LinearConstraint(
                matrix_row=matrix_row,
                rhs=rhs,
                kind="eq",
                provenance=(
                    f"Law 4 (flow-of-funds) for arc {src!r} -> {tgt!r} "
                    f"instrument {instr_val!r}, "
                    f"period {period_from_str!r} -> {period_to_str!r}"
                ),
            )
        )

    return ConstraintSet(
        constraints=constraints,
        unknowns=sorted(all_unknowns),
    )


def check_flow_funds(
    network_from: NetworkState,
    network_to: NetworkState,
    *,
    flow_terms: FlowTerms | None = None,
    revaluation_terms: RevaluationTerms | None = None,
    tol: Decimal = _DEFAULT_TOL_REL,
) -> FlowFundsResult:
    """Verify that Law 4 holds for each arc that has a known transaction flow.

    For each arc *(i, j, k)* in *flow_terms*, the residual is:

    .. math::

        r = x_{ij}^k(t+1) - x_{ij}^k(t) - F_{ij}^k - R_{ij}^k

    A violation is reported when:

    .. math::

        |r| > \\max\\bigl(
            \\text{tol} \\times |F + R|,\\; 0.1
        \\bigr)

    The absolute floor of 0.1 prevents spurious violations when the expected
    change is very small (e.g., near-zero flow on a stable arc).

    When *flow_terms* is ``None`` or empty, the check trivially passes
    (no transaction data to compare against); ``checked_count == 0``.

    Parameters
    ----------
    network_from:
        Concrete solved network for the earlier period.
    network_to:
        Concrete solved network for the later period.
    flow_terms:
        ``FlowKey → F`` in millions USD.  Only arcs with keys here are
        checked.  ``None`` or empty → trivially passes.
    revaluation_terms:
        ``FlowKey → R`` in millions USD.  Absent keys default to zero.
    tol:
        Relative tolerance as a fraction of ``|F + R|``.
        Default ``0.001`` (0.1 %).

    Returns
    -------
    FlowFundsResult
        Summary of which arcs (if any) violate Law 4.
    """
    period_from = network_from.period
    period_to = network_to.period
    period_from_str = str(period_from)
    period_to_str = str(period_to)

    if revaluation_terms is None:
        revaluation_terms = {}

    # Arc value lookups for both periods (summed over duplicates).
    arcs_from = _group_arcs_by_key(network_from.arcs, period_from)
    arcs_to = _group_arcs_by_key(network_to.arcs, period_to)

    # Count all distinct (src, tgt, instr) triples across both networks.
    all_flow_keys: set[FlowKey] = set()
    for src, tgt, instr, _ in arcs_from:
        all_flow_keys.add((src, tgt, instr))
    for src, tgt, instr, _ in arcs_to:
        all_flow_keys.add((src, tgt, instr))
    arc_count = len(all_flow_keys)

    if not flow_terms:
        return FlowFundsResult(
            period_from=period_from,
            period_to=period_to,
            satisfied=True,
            violations=[],
            arc_count=arc_count,
            checked_count=0,
        )

    violations: list[FlowFundsViolation] = []
    checked = 0

    for flow_key in sorted(flow_terms):
        src, tgt, instr_val = flow_key
        f_term = flow_terms[flow_key]
        r_term = revaluation_terms.get(flow_key, _ZERO)
        expected_change = f_term + r_term

        arc_key_from: ArcKey = (src, tgt, instr_val, period_from_str)
        arc_key_to: ArcKey = (src, tgt, instr_val, period_to_str)

        amount_from = arcs_from.get(arc_key_from, _ZERO)
        amount_to = arcs_to.get(arc_key_to, _ZERO)
        actual_change = amount_to - amount_from
        residual = actual_change - expected_change

        threshold = max(tol * abs(expected_change), _MIN_ABS_TOL)

        if abs(residual) > threshold:
            violations.append(
                FlowFundsViolation(
                    source_node_id=src,
                    target_node_id=tgt,
                    instrument_class_value=instr_val,
                    period_from=period_from,
                    period_to=period_to,
                    amount_from=amount_from,
                    amount_to=amount_to,
                    flow_term=f_term,
                    revaluation_term=r_term,
                    expected_change=expected_change,
                    actual_change=actual_change,
                    residual=residual,
                    provenance=(
                        f"Law 4 (flow-of-funds) for arc {src!r} -> {tgt!r} "
                        f"instrument {instr_val!r}, "
                        f"period {period_from_str!r} -> {period_to_str!r}: "
                        f"amount_from={amount_from}, amount_to={amount_to}, "
                        f"F={f_term}, R={r_term}, expected_change={expected_change}, "
                        f"actual_change={actual_change}, residual={residual}"
                    ),
                )
            )

        checked += 1

    return FlowFundsResult(
        period_from=period_from,
        period_to=period_to,
        satisfied=len(violations) == 0,
        violations=violations,
        arc_count=arc_count,
        checked_count=checked,
    )
